version: "3.8"
services:
    app:
        image: streamlit-docker
        build:
            dockerfile: ./Dockerfile
            context: .
        volumes:
          - .:/home/app/webapp
        environment:
            - PORT=${PORT}
        ports:
            - ${PORT}:${PORT}
